config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :jira_accounts,only: [:index, :create, :destroy, :update, :edit]

  resources :pivotal_accounts,only: [:index, :create, :destroy, :update, :edit]

  mount Sidekiq::Web => '/sidekiq'

  resources :projects, only: [:index, :new, :create, :destroy, :edit, :update] do
    member do
      get :stop
      get :start
      get :sync_project
    end
    collection do
      get :synchronize
    end
  end

  resources :project_logs, only: [:index, :show], param: :name
  resources :project_configs do
    collection do
      get :synchronize
    end
  end

  get 'sidekiq_web', to: 'landing#sidekiq', as: 'sidekiq'
  get 'about',       to: 'landing#about'
  get 'contacts',    to: 'landing#contacts'

  root to: 'landing#index'
end

app/models/jira_account.rb
class JiraAccount < ActiveRecord::Base

  has_many :projects
  validates :name,  uniqueness: true, presence: true
  validates :password , presence: true
  validates :jira_filter , presence: true
end

app/controllers/jira_accounts_controller.rb
class JiraAccountsController < ApplicationController
  before_filter :find_account, only: [:destroy, :update, :edit]

  def create
     @account = JiraAccount.create(account_params)
    if(@account)
      flash[:success] = 'Configs was successfully synchronized'
    end
    redirect_to jira_accounts_path
  end

  def index
    @accounts = JiraAccount.all
  end

  def update
    @account.update_attributes(account_params)
    redirect_to jira_accounts_path
  end

  def destroy
    @account.destroy
    redirect_to jira_accounts_path
  end

  private

  def find_account
    @account = JiraAccount.find(params[:id])
  end


  def account_params
    params[:jira_account].permit(:login, :password, :jira_filter)
  end

end

app/helpers/jira_accounts_helper.rb
module JiraAccountsHelper
end

app/views/jira_accounts/edit.haml
.container
  .col-md-10.col-md-offset-1
    %h2.white="Edit #{@account.login} pivotal account"

    = simple_form_for @account, url: pivotal_account_path, html: { method: :put, class: 'form-horizontal' } do |f|
      .form-group.col-md-2.config-form
        = f.input :name, input_html: { class: 'form-control' }
        = f.input :password, input_html: { class: 'form-control' }
        = f.input :jira_filter, input_html: { class: 'form-control' }
        = f.submit class: 'btn btn-primary'

app/views/jira_accounts/index.haml
.container.white.project_block
  = simple_form_for :jira_account do |f|
    .form-group.col-md-2.config-form
      = f.input :name,label:'Jira Login'
      = f.input :password,label:'Jira Password', :as => :string

      = f.input :jira_filter,label:'Jira Filter'
      = f.button :submit

  %h2.text-center Jira Accounts
  .col-md-12
    %table.table.project-table.table-striped
      %thead
        %tr
          %th Id
          %th login
          %th password
          %th filter
          %th Actions
      %tbody
        - @accounts.each_with_index do |account, index|
          %tr
            %td= index + 1
            %td= account.name
            %td= account.password
            %td= account.jira_filter
            %td
              = link_to 'Edit', edit_jira_account_path(account), class: 'btn btn-warning btn-xs'
              = link_to 'Delete', jira_account_url(account), class: 'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Are you sure?' }