config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :jira_accounts,only: [:index, :create, :destroy, :update, :edit]

  resources :pivotal_accounts,only: [:index, :create, :destroy, :update, :edit]

  mount Sidekiq::Web => '/sidekiq'

  resources :projects, only: [:index, :new, :create, :destroy, :edit, :update] do
    member do
      get :stop
      get :start
      get :sync_project
    end
    collection do
      get :synchronize
    end
  end

  resources :project_logs, only: [:index, :show], param: :name
  resources :project_configs do
    collection do
      get :synchronize
    end
  end

  get 'sidekiq_web', to: 'landing#sidekiq', as: 'sidekiq'
  get 'about',       to: 'landing#about'
  get 'contacts',    to: 'landing#contacts'

  root to: 'landing#index'
end

app/controllers/project_configs_controller.rb
class ProjectConfigsController < BaseController
  respond_to :js, :html
  before_filter :find_config, only: [:edit, :update, :destroy, :show]

  def index
    @configs = Project::Config.all
  end

  def new
    @config = Project::Config.new
  end

  def create
    Project::Config.create(config_params)
    respond_with(@config)
  end

  def update
    @config.update_attributes(config_params)
    respond_with(@config)
  end

  def destroy
    @config.destroy
    respond_with(@config)
  end

  def synchronize
    configs_handler = ProjectConfigsHandler.new
    if configs_handler.synchronize
      flash[:success] = 'Configs was successfully synchronized'
    else
      flash[:error] = 'Synchronization failed. Contact to administator'
    end

    redirect_to project_configs_path
  end

  private

  def find_config
    @config = Project::Config.find(params[:id])
  end

  def config_params
    params[:project_config].permit(:tracker_project_id, :jira_login, :jira_host,
                                   :jira_uri_scheme, :jira_project, :jira_port,
                                   :jira_filter, :script_first_start,
                                   :script_repeat_time, :project_id, :name,
                                   :retry_count, :jira_password, :tracker_token,
                                   jira_issue_types_attributes: [:id, :name, :jira_id, :config_id],
                                   jira_custom_fields_attributes: [:id, :name, :config_id])
  end
end

app/helpers/project_configs_helper.rb
module ProjectConfigsHelper
end

app/views/project_configs/edit.haml
.container
  .col-md-10.col-md-offset-1
    %h2.white="Edit #{@config.name} config"

    = simple_form_for @config, url: project_config_path, html: { method: :put, class: 'form-horizontal' } do |f|
      .form-group.col-md-2.config-form
        = f.input :name, input_html: { class: 'form-control' }
        = f.input :tracker_project_id, input_html: { class: 'form-control' }

      .form-group.col-md-2.config-form
        = f.input :script_first_start, input_html: { class: 'form-control' }
        = f.input :script_repeat_time, input_html: { class: 'form-control' }

      .form-group.col-md-2.config-form
        = f.input :retry_count, input_html: { class: 'form-control' }
        = f.input :jira_project, input_html: { class: 'form-control' }

      .form-group.col-md-2.config-form  
        = f.input :jira_login, input_html: { class: 'form-control' }
        = f.input :jira_filter, input_html: { class: 'form-control' }

      .form-group.col-md-2.config-form
        = f.input :jira_password, input_html: { class: 'form-control' }
        = f.input :tracker_token, input_html: { class: 'form-control' }

      .form-group.col-md-3.config-form  
        = f.input :jira_host, input_html: { class: 'form-control' }
        = f.input :jira_uri_scheme, input_html: { class: 'form-control' }
        = f.input :jira_port, input_html: { class: 'form-control' }

      .form-group.col-md-6.config-form.pull-right
        %h4.text-center Jira Custom Fields
        = f.simple_fields_for :jira_custom_fields do |field|
          .col-md-5.custom-fields
            .col-md-9
              = field.input :name, label: false
              = field.input :value, label: false
            = link_to 'X', '#', class: 'btn btn-small btn-danger'

        .col-md-8.pull-right.text-right
          = link_to 'Add Field', '#', class: 'btn btn-success'

      .form-group.col-md-8.text-center
        = f.submit class: 'btn btn-primary'

app/views/project_configs/index.haml
.container.white.project_block
  %h2.text-center Project Configs
  .pull-right.btn-synchronize
    / TODO: Uncoment when finished
    / # = link_to 'New Config', new_project_config_path, class: 'btn btn-primary btn-large'
    = link_to 'Synchronize Configs', synchronize_project_configs_path, class: 'btn btn-success btn-large'

  .col-md-12
    %table.table.project-table.table-striped
      %thead
        %tr
          %th Id
          %th Name
          %th Jira project
          %th Jira filter
          %th Pivotal project id
          %th Actions
      %tbody
        - @configs.each_with_index do |config, index|
          %tr
            %td= index + 1
            %td= link_to config.name, project_config_path(config), class: 'table-link'
            %td= config.jira_project
            %td= config.jira_filter
            %td= config.tracker_project_id
            %td
              = link_to 'Show', project_config_path(config), class: 'btn btn-success btn-xs'
              = link_to 'Edit', edit_project_config_path(config), class: 'btn btn-warning btn-xs'
              = link_to 'Delete', project_config_path(config), class: 'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Are you sure?' }

app/views/project_configs/show.haml
.container.project_block
  %h1.text-center= @config.name.camelcase

  .col-md-6.col-md-offset-3
    %table.table.project-table.table-striped
      %tbody
        %tr
          %td tracker_project_id
          %td= @config.tracker_project_id
        %tr
          %td jira_login
          %td= @config.jira_login
        %tr
          %td jira_host
          %td= @config.jira_host
        %tr
          %td jira_uri_scheme
          %td= @config.jira_uri_scheme
        %tr
          %td jira_port
          %td= @config.jira_port
        %tr
          %td jira_filter
          %td= @config.jira_filter
        %tr
          %td script_first_start
          %td= @config.script_first_start
        %tr
          %td script_repeat_time
          %td= @config.script_repeat_time
        %tr
          %td jira_password
          %td= @config.jira_password
        %tr
          %td tracker_token
          %td= @config.tracker_token
        %tr{style: 'border-top: 3px solid #dddddd;'}
          %td jira_custom_fields
          %td

        - @config.jira_custom_fields.each do |custom_field|
          %tr
            %td
            %td= custom_field.name
        %tr{style: 'border-top: 3px solid #dddddd;'}
          %td jira_issue_types
          %td
        - @config.jira_issue_types.each do |issue_type|
          %tr
            %td
            %td
              = issue_type.name + ':'
              = issue_type.jira_id