config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :jira_accounts,only: [:index, :create, :destroy, :update, :edit]

  resources :pivotal_accounts,only: [:index, :create, :destroy, :update, :edit]

  mount Sidekiq::Web => '/sidekiq'

  resources :projects, only: [:index, :new, :create, :destroy, :edit, :update] do
    member do
      get :stop
      get :start
      get :sync_project
    end
    collection do
      get :synchronize
    end
  end

  resources :project_logs, only: [:index, :show], param: :name
  resources :project_configs do
    collection do
      get :synchronize
    end
  end

  get 'sidekiq_web', to: 'landing#sidekiq', as: 'sidekiq'
  get 'about',       to: 'landing#about'
  get 'contacts',    to: 'landing#contacts'

  root to: 'landing#index'
end

app/views/shared/_navbar.html.haml
/ Navigation
%nav.navbar.navbar-inverse.navbar-fixed-top{ role: 'navigation' }
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{ "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button" }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'J2P', root_path, class: 'navbar-brand'
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        = link_to_menu 'Projects',        projects_path
        = link_to_menu 'Project configs', project_configs_path
        = link_to_menu 'Sidekiq',         sidekiq_path
        = link_to_menu 'About',           about_path
        = link_to_menu 'Contact',         contacts_path
        = link_to_menu 'Login',           root_path

    / /.navbar-collapse
  / /.container