config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :jira_accounts,only: [:index, :create, :destroy, :update, :edit]

  resources :pivotal_accounts,only: [:index, :create, :destroy, :update, :edit]

  mount Sidekiq::Web => '/sidekiq'

  resources :projects, only: [:index, :new, :create, :destroy, :edit, :update] do
    member do
      get :stop
      get :start
      get :sync_project
    end
    collection do
      get :synchronize
    end
  end

  resources :project_logs, only: [:index, :show], param: :name
  resources :project_configs do
    collection do
      get :synchronize
    end
  end

  get 'sidekiq_web', to: 'landing#sidekiq', as: 'sidekiq'
  get 'about',       to: 'landing#about'
  get 'contacts',    to: 'landing#contacts'

  root to: 'landing#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_one :config, class_name: 'Project::Config', dependent: :destroy
  has_one :log
  belongs_to :pivotal_account
  belongs_to :jira_account
  has_many :jira_custom_fields, class_name: 'Jira::CustomField'
  has_many :jira_issue_types, class_name: 'Jira::IssueType'

  scope :projects_to_sync, -> { where(active: true) }

  def log_name
    name.underscore.gsub(' ', '_')
  end

  def worker_status
    Sidekiq::Status::status(current_job_id)
  end
end

app/models/project/config.rb
class Project::Config < ActiveRecord::Base
  self.table_name = 'configs'
  has_many :jira_custom_fields, class_name: 'Jira::CustomField'
  has_many :jira_issue_types, class_name: 'Jira::IssueType'

  belongs_to :project

  validates :name,  uniqueness: true

  accepts_nested_attributes_for :jira_issue_types
  accepts_nested_attributes_for :jira_custom_fields

  after_update :update_config_file
  before_destroy :delete_config_file

  def delete_config_file
    config_path = Rails.root.join "config/integrations/#{name}.yml"

    File.delete(config_path) if File.exist?(config_path)
  end

  def update_config_file
    return unless changes.except(:updated_at).any?

    attributes = self.attributes.except('updated_at', 'created_at', 'project_id', 'id', 'name')

    if changes.include?(:name)
      attributes.merge!(old_name: changes[:name].first, new_name: changes[:name].last)
    else
      attributes.merge!(old_name: name)
    end

    ProjectConfigsHandler.new.update_config_file(attributes)
  end
end

app/models/project/log.rb
class Project::Log < ActiveRecord::Base
  belongs_to :project
end

app/controllers/projects_controller.rb
class ProjectsController < BaseController
  before_filter :find_project, only: [:start, :stop, :sync_project, :destroy, :update, :edit]

  def index
    @projects = Project.all
  end

  def new
    @project=Project.new
    render 'edit'
  end

  def create
    Project.create(project_params)
    redirect_to projects_path
  end

  def update
    @project.update_attributes(project_params)

    redirect_to projects_path
  end

  def destroy
    @project.destroy

    redirect_to projects_path
  end

  def sync_project
    SyncWorker.perform_async(@project.id)

    render nothing: true
  end

  def status
    @projects = Project.all
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params[:project].permit(:name, :tracker_project_id,
                            :jira_project, :pivotal_account_id, :jira_account_id, :active )
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_label(status)
    content_tag(:span, "#{status}", class: 'label label-success')
  end
end

app/views/projects/edit.haml
.container
  .col-md-10.col-md-offset-1
    %h2.black="Edit #{@project.name if @project} config"

    = simple_form_for @project do |f|
      .form-group.col-md-4.config-form
        = f.input :name, input_html: { class: 'form-control' }
        = f.input :tracker_project_id
        = f.input :jira_project, input_html: { class: 'form-control' }
        = f.input :pivotal_account_id, collection: PivotalAccount.all
        = f.input :jira_account_id, collection: JiraAccount.all
        = f.submit class: 'btn btn-primary'

app/views/projects/index.html.haml
.container.white.project_block.projects-index
  %h2.text-center.col-md-12 Projects
  .col-md-12
    .pull-right.btn-synchronize
    / # = link_to 'New Config', new_project_config_path, class: 'btn btn-primary btn-large'
    = link_to 'New project', new_project_path, class: 'btn btn-success btn-large'
    %table.table.project-table.table-striped
      %thead
        %tr
          %th Id
          %th Name
          %th Config Name
          %th Pid
          %th Last Update
          %th Log
          %th Status
          %th Actions
          %th Active
      %tbody
        - @projects.each_with_index do |project, index|
          %tr
            %td= index + 1
            %td= project.jira_project
            %td= project.pid
            %td= project.last_update
            %td= link_to project.log_name, project_log_path(project.log_name), class: 'table-link'
            %td{ class: "status-#{project.id}" }= project_label(project.worker_status)
            %td
              .col-md-12
                = link_to '#', id: "id-#{project.id}", class: 'action-link white force-sync', data: { project_id: project.id } do
                  %i.fa.fa-refresh
                = link_to project_path(project), id: "id-#{project.id}", class: 'action-link white', method: :delete do
                  %i.fa.fa-times
                = link_to 'Edit',  edit_project_path(project), class: 'btn btn-warning btn-xs'
            %td
              = check_box_tag "active-#{project.id}", project.id, project.active, class: 'project-active', data: { project_id: project.id }

app/views/projects/status.js.haml
- @projects.each do |project|
  $(".status-#{project.id}").html( "<span class='label label-success'>#{project.worker_status}</span>" )